# Generated by Django 6.0.6 on 2026-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_session',
            field=models.CharField(blank=True, help_text='Example: Spring 2026, Summer 2026, Fall 2026', max_length=50, null=True),
        ),
    ]
