# Generated by Django 6.0.6 on 2026-07-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_admission_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
