# Generated by Django 6.0.6 on 2026-07-03 13:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('finance', '0001_initial'),
        ('students', '0004_studentprofile_admission_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Example: Cash, Bank, bKash, Card', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.studentfee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='waiver_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='waiver',
            name='source',
            field=models.CharField(choices=[('gpa', 'GPA Based'), ('special', 'Special Waiver'), ('manual', 'Manual Adjustment')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='waiver',
            name='student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waivers', to='finance.studentfee'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount after waiver.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProgramFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('diploma', 'Diploma'), ('postgraduate', 'Postgraduate')], default='undergraduate', max_length=30)),
                ('duration_text', models.CharField(blank=True, help_text='Example: 4 Yr / 8 Sem / 165', max_length=100, null=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('semester_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_semesters', models.PositiveIntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department__code', 'program_name'],
                'unique_together': {('program_name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='StudentFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_gpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('hsc_gpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('combined_gpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('semester_fee_before_waiver', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('regular_waiver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatic waiver based on SSC + HSC GPA.', max_digits=12)),
                ('special_waiver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual special waiver approved by Super Admin.', max_digits=12)),
                ('final_semester_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_semesters', models.PositiveIntegerField(default=8)),
                ('total_semester_fee_after_waiver', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total_after_waiver', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_profiles', to=settings.AUTH_USER_MODEL)),
                ('program_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.programfeestructure')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='students.studentprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_financial_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaiverPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gpa_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('waiver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Semester-wise waiver amount.', max_digits=12)),
                ('note', models.CharField(blank=True, help_text='Example: GPA 10 out of 10', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_fee', models.ForeignKey(blank=True, help_text='Leave blank if this rule applies to all programs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiver_policies', to='finance.programfeestructure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-gpa_min', '-gpa_max'],
            },
        ),
    ]
