# Generated by Django 6.0.6 on 2026-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_payment_method_payment_student_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverpolicy',
            name='admission_category',
            field=models.CharField(choices=[('regular', 'Regular'), ('diploma', 'Diploma'), ('masters', 'Masters'), ('special', 'Special')], default='regular', max_length=30),
        ),
    ]
