# Generated by Django 6.0.6 on 2026-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_waiverpolicy_admission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinancialprofile',
            name='admission_category',
            field=models.CharField(choices=[('regular', 'Regular'), ('diploma', 'Diploma'), ('masters', 'Masters'), ('special', 'Special')], default='regular', max_length=30),
        ),
    ]
