# Generated by Django 6.0.6 on 2026-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_courseoffering_faculty_delete_program'),
        ('faculty', '0001_initial'),
        ('students', '0003_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mark',
            name='raw_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'course_offering')},
        ),
    ]
