# Generated by Django 6.0.6 on 2026-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_mark_grade_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accepting_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
