# Generated by Django 6.0.6 on 2026-07-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_mark_last_updated_at_mark_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['course_offering__course__code', 'student__student_id']},
        ),
    ]
