# Generated by Django 6.0.6 on 2026-07-01 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='University of Global Village', max_length=200)),
                ('short_name', models.CharField(default='UGV', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system_settings/')),
                ('current_academic_session', models.CharField(blank=True, help_text='Example: Summer 2026', max_length=100, null=True)),
                ('result_publication_note', models.TextField(blank=True, default='This result is published electronically by the university authority.', null=True)),
                ('admit_card_note', models.TextField(blank=True, default='Students must bring this admit card to the examination hall.', null=True)),
                ('payment_instruction', models.TextField(blank=True, default='Please clear all dues before the payment deadline.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
