# Generated by Django 6.0.6 on 2026-07-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='current_semester',
        ),
    ]
