# Generated by Django 6.0.6 on 2026-06-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('dept_head', 'Department Head'), ('exam_controller', 'Exam Controller'), ('accounts', 'Accounts Officer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='student', max_length=30),
        ),
    ]
