# Generated by Django 6.0.6 on 2026-07-07 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('accounts', '0003_user_address_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='Example: Lecturer, Assistant Professor, Accounts Officer, Exam Controller', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique ID for faculty/staff/admin users. Example: FAC-CSE-001, ACC-001, EXAM-001', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_department',
            field=models.ForeignKey(blank=True, help_text='Department for faculty, department head, or staff if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='academics.department'),
        ),
    ]
