# Generated by Django 6.0.6 on 2026-06-27 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('exams', '0002_hallduty_seatplan_resultpublication'),
        ('students', '0003_courseregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final')], default='final', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='admitcard',
            unique_together={('student', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='examroutine',
            unique_together={('course_offering', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='hallduty',
            unique_together={('faculty', 'exam_routine', 'duty_room')},
        ),
        migrations.AlterUniqueTogether(
            name='seatplan',
            unique_together={('student', 'course_offering', 'exam_type')},
        ),
    ]
