# Generated by Django 6.0.6 on 2026-07-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('exams', '0003_alter_admitcard_exam_type_and_more'),
        ('faculty', '0005_mark_last_updated_at_mark_last_updated_by_and_more'),
        ('students', '0005_studentprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('old_class_test', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('old_assignment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('old_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('old_midterm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('old_final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_class_test', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_assignment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_midterm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='faculty.mark')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_result_corrections', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
