# Generated by Django 6.0.6 on 2026-07-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_resultcorrectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroutine',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('recovery', 'Recovery')], max_length=20),
        ),
    ]
