# Generated by Django 6.0.6 on 2026-07-12 17:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('exams', '0005_alter_examroutine_exam_type'),
        ('faculty', '0006_alter_assignment_options_and_more'),
        ('students', '0005_studentprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcorrectionrequest',
            name='exam_attachment',
            field=models.FileField(blank=True, null=True, upload_to='result_corrections/exam_controller/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='resultcorrectionrequest',
            name='exam_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultcorrectionrequest',
            name='exam_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultcorrectionrequest',
            name='exam_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_reviewed_result_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultcorrectionrequest',
            name='faculty_attachment',
            field=models.FileField(blank=True, null=True, upload_to='result_corrections/faculty/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='resultcorrectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('faculty_submitted', 'Submitted by Faculty'), ('exam_verified', 'Verified by Exam Controller'), ('exam_rejected', 'Rejected by Exam Controller'), ('approved', 'Approved by Super Admin'), ('rejected', 'Rejected by Super Admin')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentMarkReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_components', models.JSONField(blank=True, default=list, help_text='Mark components selected by the student, such as class_test, assignment, attendance, midterm, or final.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mark_review_requests/student/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('pending_faculty', 'Pending Faculty Review'), ('faculty_rejected', 'Rejected by Faculty'), ('faculty_confirmed', 'Confirmed by Faculty')], default='pending_faculty', max_length=30)),
                ('faculty_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mark_review_requests', to='academics.courseoffering')),
                ('faculty_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_mark_requests', to=settings.AUTH_USER_MODEL)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_review_requests', to='faculty.mark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_review_requests', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resultcorrectionrequest',
            name='student_review_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='exams.studentmarkreviewrequest'),
        ),
    ]
