# Generated by Django 6.0.6 on 2026-07-01 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursematerial'),
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-published_at', '-id']},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notice_attachments/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('exam', 'Exam'), ('payment', 'Payment'), ('admission', 'Admission'), ('event', 'Event'), ('urgent', 'Urgent')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Students'), ('faculty', 'Faculty'), ('department', 'Specific Department'), ('batch', 'Specific Batch'), ('exam_controller', 'Exam Controller'), ('accounts', 'Accounts Office'), ('admin', 'Admin')], default='all', max_length=30),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
